# Site settings
title: Sahdeep Singh
description: My Resume Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sahdeep Singh
user_description: A versatile,high energy android developer (kind of noob),every time thinks about creating something creative.Interests in AI and android only.
user_title: Android Developer
email: sahdeepsingh98@gmail.com
twitter_username: singh_sahdeep
github_username:  sahdeepsingh
gitlab_username: sahdeepsingh
gplus_username:  102836403719188208803

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
